apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fms-ws-maven-dev
spec:
  storageClassName: nasoft-nfs-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
