kind: Deployment
apiVersion: apps/v1
metadata:
  name: reporting
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      restartPolicy: Always
      serviceAccountName: maxula-sa
      containers:
        - resources: {}
          name: reporting
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: host
            - name: FMSWS_HOST
              valueFrom:
                configMapKeyRef:
                  name: fmsws-conf
                  key: host
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          ports:
            - containerPort: 8086
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: reporting
              mountPath: /reporting
          image: amara11/maxulareporting:latest
      serviceAccount: maxula-sa
      volumes:
        - name: reporting
          persistentVolumeClaim:
            claimName: reporting-pvc

status: {}
